out_dir: results
metric_best: mae
metric_agg: argmin
dataset:
  format: PowerGrid-size
  name: tr20_teTexas
  train_dataset: dataset20
  test_dataset: Texas
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+NetSci
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 10
  edge_encoder_bn: False

Netsci_NetSci:
  enable: True
  model: Linear #Linear; mlp
  dim_pe: 3
  raw_norm_type: BatchNorm
#  number_metrics: 46
  layers: 1
  SelectedMetrics: [9,10] #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]
  # 0：P； 1：AP； 2：AAP; 3：AAAP; 4:row_sum_AA; 5：row_sum_AAA; 6：degree; 7：degree_centrality; 8：neighbor_degree_min;
  # 9：neighbor_degree_max; 10：clustering; 11：betweenness_centrality; 12：closeness_centrality; 13：load_centrality;
  # 14：eigenvector_centrality; 15：katz_centrality; 16：second_order_centrality; 17：current_flow_closeness_centrality;
  # 18：current_flow_betweenness_centrality; 19：average_neighbor_degree; 20：harmonic_centrality; 21：square_clustering;
  # 22：eccentricity; 23：bulk; 24：root; 25：dense_sprout; 26：sparse_sprout; 27：inner_tree_node; 28：proper_leaf;
  # 29：fiedler_vector; 30：node_connected_to_max_load_line; 31：max_load_connected_lines; 32：min_load_connected_lines; 33：mean_load_connected_lines;
  # 34：resistance_distance_centrality; 35：degree_assortativity_coefficient; 36：transitivity; 37：diameter;
  # 38：attribute_assortativity_coefficient_P; 39：kirchhoff_index; 40：resistance_distance_kirchhoff_index; 41：inverse_algebraic_connectivity;
  # 42：eigen_ratio; 43：power_sign_ratio; 44：maximal_line_load; 45：universal_kuramoto_order_parameter;

train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: NSGNNModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
nsgnn:
  layer_type: SAGE
  layers: 10
  n_heads: 4
  dim_hidden: 64
  dropout: 0.3
  layer_norm: False
  batch_norm: True
gnn:
  head: inductive_NetSci_node
  layers_pre_mp: 0
  layers_post_mp: 8
  dim_inner: 64  # `nsgnn.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: sum #mean
  normalize_adj: False
  loss_self_head: None
optim:
  optimizer: adam
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 3
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5